// <auto-generated />
using System;
using ForumSystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumSystem.DataAccess.Migrations
{
    [DbContext(typeof(ForumSystemContext))]
    [Migration("20230716095219_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Bitcon is the best!",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3455),
                            IsDeleted = false,
                            PostId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bitcoin is trash",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3468),
                            IsDeleted = false,
                            PostId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Ethereum is better",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3471),
                            IsDeleted = false,
                            PostId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Ripple is the new best crypto",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3473),
                            IsDeleted = false,
                            PostId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "I totally agree! Investing in cryptocurrency is like playing the lottery, except with worse odds!",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3475),
                            IsDeleted = false,
                            PostId = 11,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Haha, so true! The cryptocurrency market is definitely a rollercoaster ride of emotions!",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3479),
                            IsDeleted = false,
                            PostId = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "I've been scammed before too. It's so important to do your research before investing in cryptocurrency!",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3481),
                            IsDeleted = false,
                            PostId = 13,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            Content = "I've had my coins stolen by hackers before. It's so important to take security measures to protect your investments!",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3483),
                            IsDeleted = false,
                            PostId = 14,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            Content = "The regulatory environment for cryptocurrency is definitely uncertain. It's important to stay informed and be prepared for changes.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3486),
                            IsDeleted = false,
                            PostId = 15,
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            Content = "Market manipulation is such a big problem in the cryptocurrency world. It's important to be cautious and do your research before investing.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3490),
                            IsDeleted = false,
                            PostId = 16,
                            UserId = 6
                        },
                        new
                        {
                            Id = 11,
                            Content = "I've had an exchange I used go bankrupt before. It's so important to choose a reputable exchange and diversify your investments!",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3493),
                            IsDeleted = false,
                            PostId = 17,
                            UserId = 7
                        },
                        new
                        {
                            Id = 12,
                            Content = "Technical failures can definitely cause problems for cryptocurrency investors. It's important to keep up to date with developments and updates.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3496),
                            IsDeleted = false,
                            PostId = 18,
                            UserId = 8
                        },
                        new
                        {
                            Id = 13,
                            Content = "I've made some risky investments in cryptocurrency before because I didn't fully understand the technology or market. Educating yourself is so important!",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3498),
                            IsDeleted = false,
                            PostId = 19,
                            UserId = 9
                        },
                        new
                        {
                            Id = 14,
                            Content = "The competition in the cryptocurrency market is intense! It's important to stay informed and make smart investment decisions.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3501),
                            IsDeleted = false,
                            PostId = 20,
                            UserId = 10
                        },
                        new
                        {
                            Id = 15,
                            Content = "I totally agree! Investing in cryptocurrency can be a high-risk venture, but it can also be very rewarding if you do your research and make smart decisions.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3503),
                            IsDeleted = false,
                            PostId = 11,
                            UserId = 11
                        },
                        new
                        {
                            Id = 16,
                            Content = "The volatility of the cryptocurrency market can definitely be nerve-wracking, but it can also provide opportunities for savvy investors.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3506),
                            IsDeleted = false,
                            PostId = 12,
                            UserId = 12
                        },
                        new
                        {
                            Id = 17,
                            Content = "Crypto scams are the worst! I've lost money before because I didn't do my research. Always be cautious when investing in cryptocurrency.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3508),
                            IsDeleted = false,
                            PostId = 13,
                            UserId = 13
                        },
                        new
                        {
                            Id = 18,
                            Content = "Hackers are definitely a big threat to cryptocurrency investors. It's so important to take security measures to protect your investments!",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3512),
                            IsDeleted = false,
                            PostId = 14,
                            UserId = 14
                        },
                        new
                        {
                            Id = 19,
                            Content = "The regulatory environment for cryptocurrency is always changing. It's important to stay informed and be prepared for any changes that may come.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3514),
                            IsDeleted = false,
                            PostId = 15,
                            UserId = 15
                        },
                        new
                        {
                            Id = 20,
                            Content = "Market manipulation is such a big problem in the cryptocurrency world. Always do your research and be cautious when investing.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3517),
                            IsDeleted = false,
                            PostId = 16,
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            Content = "Choosing a reputable exchange is so important! I've had friends lose money because they used an exchange that went bankrupt.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3519),
                            IsDeleted = false,
                            PostId = 17,
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            Content = "Technical failures can definitely cause problems for investors. Keeping up to date with developments and updates is crucial.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3521),
                            IsDeleted = false,
                            PostId = 18,
                            UserId = 3
                        },
                        new
                        {
                            Id = 23,
                            Content = "Educating yourself before investing in cryptocurrency is so important! I've made some risky investments in the past because I didn't fully understand the market.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3675),
                            IsDeleted = false,
                            PostId = 19,
                            UserId = 4
                        },
                        new
                        {
                            Id = 24,
                            Content = "Competition in the cryptocurrency market is fierce! Staying informed and making smart investment decisions is key.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3678),
                            IsDeleted = false,
                            PostId = 20,
                            UserId = 5
                        },
                        new
                        {
                            Id = 25,
                            Content = "I totally agree! Investing in cryptocurrency can be risky, but it can also be very rewarding if you do your research and make smart decisions.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3680),
                            IsDeleted = false,
                            PostId = 11,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId", "CommentId")
                        .IsUnique()
                        .HasFilter("[PostId] IS NOT NULL AND [CommentId] IS NOT NULL");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3683),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3686),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3689),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3691),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3694),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3697),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3699),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3701),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3704),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3707),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3709),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 2,
                            UserId = 14
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3711),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3714),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3717),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3719),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3721),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3724),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3727),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3729),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3732),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 10,
                            UserId = 10
                        },
                        new
                        {
                            Id = 21,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3734),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 22,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3736),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 23,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3739),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 3,
                            UserId = 13
                        },
                        new
                        {
                            Id = 24,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3741),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 25,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3743),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 26,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3745),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 11,
                            UserId = 7
                        },
                        new
                        {
                            Id = 27,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3748),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 12,
                            UserId = 8
                        },
                        new
                        {
                            Id = 28,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3750),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 13,
                            UserId = 9
                        },
                        new
                        {
                            Id = 29,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3752),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 14,
                            UserId = 10
                        },
                        new
                        {
                            Id = 30,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3754),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 15,
                            UserId = 11
                        },
                        new
                        {
                            Id = 31,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3757),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 16,
                            UserId = 12
                        },
                        new
                        {
                            Id = 32,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3759),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 17,
                            UserId = 13
                        },
                        new
                        {
                            Id = 33,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3761),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 18,
                            UserId = 14
                        },
                        new
                        {
                            Id = 34,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3770),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 19,
                            UserId = 15
                        },
                        new
                        {
                            Id = 35,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3772),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 20,
                            UserId = 7
                        },
                        new
                        {
                            Id = 36,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3774),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 11,
                            UserId = 8
                        },
                        new
                        {
                            Id = 37,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3777),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 12,
                            UserId = 9
                        },
                        new
                        {
                            Id = 38,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3779),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 13,
                            UserId = 10
                        },
                        new
                        {
                            Id = 39,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3781),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 14,
                            UserId = 11
                        },
                        new
                        {
                            Id = 40,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3784),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 15,
                            UserId = 12
                        },
                        new
                        {
                            Id = 41,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3786),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 16,
                            UserId = 13
                        },
                        new
                        {
                            Id = 42,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3789),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 17,
                            UserId = 14
                        },
                        new
                        {
                            Id = 43,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3791),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 18,
                            UserId = 15
                        },
                        new
                        {
                            Id = 44,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3793),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 19,
                            UserId = 7
                        },
                        new
                        {
                            Id = 45,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3795),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 20,
                            UserId = 8
                        },
                        new
                        {
                            Id = 46,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3798),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 11,
                            UserId = 9
                        },
                        new
                        {
                            Id = 47,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3800),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 12,
                            UserId = 10
                        },
                        new
                        {
                            Id = 48,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3802),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 13,
                            UserId = 11
                        },
                        new
                        {
                            Id = 49,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3805),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 14,
                            UserId = 12
                        },
                        new
                        {
                            Id = 50,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3807),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 15,
                            UserId = 13
                        },
                        new
                        {
                            Id = 51,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3809),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 16,
                            UserId = 14
                        },
                        new
                        {
                            Id = 52,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3812),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 17,
                            UserId = 15
                        },
                        new
                        {
                            Id = 53,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3815),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 18,
                            UserId = 7
                        },
                        new
                        {
                            Id = 54,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3817),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 19,
                            UserId = 8
                        },
                        new
                        {
                            Id = 55,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3819),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 20,
                            UserId = 9
                        },
                        new
                        {
                            Id = 56,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3822),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 11,
                            UserId = 10
                        },
                        new
                        {
                            Id = 57,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3824),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 12,
                            UserId = 11
                        },
                        new
                        {
                            Id = 58,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3827),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 13,
                            UserId = 12
                        },
                        new
                        {
                            Id = 59,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3829),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 14,
                            UserId = 13
                        },
                        new
                        {
                            Id = 60,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3831),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 15,
                            UserId = 14
                        },
                        new
                        {
                            Id = 61,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3834),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 16,
                            UserId = 15
                        },
                        new
                        {
                            Id = 62,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3836),
                            IsDeleted = false,
                            IsDislike = false,
                            PostId = 17,
                            UserId = 7
                        },
                        new
                        {
                            Id = 63,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3838),
                            IsDeleted = false,
                            IsDislike = true,
                            PostId = 18,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "A non-convertible currency is one that one cannot exchange that currency on the international foreign exchange market. Outside the country, this currency has no value — it may also be referred to as locked money. For example, the Indian rupee is a semi-non convertible currency outside of India while dollars can be exchanged in all countries around the world.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3391),
                            IsDeleted = false,
                            Title = "WILL BITCOIN BE USED BY THE ENTIRE WORLD?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "If governments decide to opt for a non-convertible currency, it is mainly to prevent capital flight abroad. In effect, by preventing convertibility, residents are then \"forced\" to use the currency in the country. Although the currency cannot leave the territory, it is nevertheless possible via complex financial instruments such as non-deliverable forwards (NDFs).",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3397),
                            IsDeleted = false,
                            Title = "WHY DO SOME COUNTRIES OPT FOR NON-CONVERTIBLE CURRENCIES?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Since then, the idea of ​​a single currency or a return to the gold standard has been put back on the table. It’s not a new idea, actually.\r\n\r\nDuring the Bretton Woods agreement, John Mayard Keynes proposed the creation of an international currency called the bancor, fixed by a basket of strong currencies of industrialized countries. His proposal was not accepted but his idea has continued across generations of economists.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3399),
                            IsDeleted = false,
                            Title = "THE IDEA OF ​​A SINGLE WORLD CURRENCY.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Content = "f there were no more national currencies, foreign exchange market-based problems and conversion fees would end immediately. Countries would no longer have a monetary barrier and could trade more freely. This would improve and increase international trade. All nations would benefit, especially countries with fragile currencies because there would be no more exchange risk.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3403),
                            IsDeleted = false,
                            Title = "WHAT WOULD BE THE BENEFITS OF A WORLD CURRENCY?",
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Content = "The world’s reserve currency must have a central authority, like the US Federal Reserve, regulating the USD’s supply and usage in global economies. However, Bitcoin is a decentralized currency without any central entity. Instead, it runs on a decentralized blockchain network that validates transactions and mints new coins based on the Bitcoin protocol.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3406),
                            IsDeleted = false,
                            Title = "No Central Authority ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "Monero was launched in 2014 as a privacy-focused coin and, according to many, still offers the greatest degree of transaction anonymity compared to other cryptocurrencies.\r\n\r\nAlthough the Monero blockchain is open-source and operates as a decentralized, public network, all transaction details, including sender and recipient addresses and amounts, are cloaked. Monero achieves this using a combination of ring signatures and stealth addresses.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3410),
                            IsDeleted = false,
                            Title = "Monero",
                            UserId = 10
                        },
                        new
                        {
                            Id = 7,
                            Content = "Zcash was created in 2014 as a fork of the Bitcoin code named Zerocash, which was conceived with privacy in mind. The development was later taken over by the Electric Coin Company in 2016, which still maintains Zcash to this day.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3413),
                            IsDeleted = false,
                            Title = "Zcash",
                            UserId = 11
                        },
                        new
                        {
                            Id = 8,
                            Content = "Dash allows users to implement private transactions via a feature called PrivateSend, which cloaks transaction details. The project was started in 2014 under the name Darkcoin, but rebranded to Dash with a focus on payments in 2015.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3416),
                            IsDeleted = false,
                            Title = "Dash",
                            UserId = 12
                        },
                        new
                        {
                            Id = 9,
                            Content = "Privacy coins are often viewed as higher-risk assets by the international Financial Action Task Force (FATF) and by national AML authorities. Some jurisdictions, such as Dubai, outlaw the use of privacy coins entirely.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3418),
                            IsDeleted = false,
                            Title = "Privacy Coins and Regulation",
                            UserId = 13
                        },
                        new
                        {
                            Id = 10,
                            Content = "Privacy coins like Monero have no transaction history associated with them, making them more fungible than currencies like Bitcoin. Although BTC is generally considered to be a fungible asset, Bitcoin’s UTXO model means that it’s possible to trace the history of all BTC back to the point it was mined.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3422),
                            IsDeleted = false,
                            Title = "Benefits and Risks of Using Privacy Coins",
                            UserId = 14
                        },
                        new
                        {
                            Id = 20,
                            Content = "The cryptocurrency market is highly competitive, with new coins and technologies emerging regularly. I've seen this competition impact the value of my existing coins and result in financial losses.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3425),
                            IsDeleted = false,
                            Title = "The Impact of Competition on My Cryptocurrency Investments",
                            UserId = 14
                        },
                        new
                        {
                            Id = 11,
                            Content = "Investing in cryptocurrency is like playing the lottery, except the odds are even worse and the prize is imaginary internet money. Trust me, I've learned the hard way.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3427),
                            IsDeleted = false,
                            Title = "The Risk of Investing in Cryptocurrency: A Cautionary Tale",
                            UserId = 13
                        },
                        new
                        {
                            Id = 12,
                            Content = "The cryptocurrency market is like a rollercoaster ride, except instead of screaming in excitement, you're screaming in terror as your life savings plummet in value. Buckle up, folks.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3430),
                            IsDeleted = false,
                            Title = "Cryptocurrency: A Rollercoaster Ride of Emotions",
                            UserId = 14
                        },
                        new
                        {
                            Id = 13,
                            Content = "Scammers love cryptocurrency almost as much as they love taking money from gullible investors. Always do your research before investing, or you might end up like me: broke and embarrassed.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3433),
                            IsDeleted = false,
                            Title = "Crypto Scams: A Fool and Their Money are Soon Parted",
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            Content = "Hackers love cryptocurrency almost as much as they love stealing it from unsuspecting investors. Protect your investments, or you might end up like me: refreshing your empty wallet and crying into your keyboard.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3436),
                            IsDeleted = false,
                            Title = "Hackers and Cryptocurrency: A Match Made in Cybercrime Heaven",
                            UserId = 7
                        },
                        new
                        {
                            Id = 15,
                            Content = "The regulatory environment for cryptocurrency is like a game of cat and mouse, except the cat is a government agency and the mouse is your life savings. Good luck out there.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3438),
                            IsDeleted = false,
                            Title = "Cryptocurrency and Regulation: A Game of Cat and Mouse",
                            UserId = 13
                        },
                        new
                        {
                            Id = 16,
                            Content = "Market manipulation in the cryptocurrency world is like a game of musical chairs, except when the music stops, you're left standing without a chair or your life savings. Don't be like me, folks.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3441),
                            IsDeleted = false,
                            Title = "Market Manipulation and Cryptocurrency: A Tale of Boom and Bust",
                            UserId = 14
                        },
                        new
                        {
                            Id = 17,
                            Content = "If a cryptocurrency exchange goes bankrupt, it's like a game of hot potato, except the potato is your life savings and it just exploded in your hands. Choose your exchange wisely, my friends.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3445),
                            IsDeleted = false,
                            Title = "Crypto Exchange Insolvency: When the Music Stops",
                            UserId = 15
                        },
                        new
                        {
                            Id = 18,
                            Content = "Technical failures in cryptocurrency are like a computer virus, except instead of deleting your files, it deletes your life savings. Keep those updates coming, developers.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3449),
                            IsDeleted = false,
                            Title = "Technical Failures in Cryptocurrency: When the Code Hits the Fan",
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            Content = "Investing in cryptocurrency without understanding the technology or market is like trying to bake a cake without a recipe. You might get lucky, but chances are you'll end up with a burnt mess and a lot of regret.",
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3452),
                            IsDeleted = false,
                            Title = "Uninformed Investing in Cryptocurrency: A Recipe for Disaster",
                            UserId = 13
                        });
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.PostTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostId = 1,
                            TagId = 3
                        },
                        new
                        {
                            Id = 2,
                            PostId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 3,
                            PostId = 2,
                            TagId = 3
                        },
                        new
                        {
                            Id = 4,
                            PostId = 3,
                            TagId = 3
                        },
                        new
                        {
                            Id = 5,
                            PostId = 4,
                            TagId = 1
                        },
                        new
                        {
                            Id = 6,
                            PostId = 5,
                            TagId = 2
                        },
                        new
                        {
                            Id = 7,
                            PostId = 6,
                            TagId = 3
                        },
                        new
                        {
                            Id = 8,
                            PostId = 7,
                            TagId = 4
                        },
                        new
                        {
                            Id = 9,
                            PostId = 8,
                            TagId = 1
                        },
                        new
                        {
                            Id = 10,
                            PostId = 9,
                            TagId = 2
                        },
                        new
                        {
                            Id = 11,
                            PostId = 10,
                            TagId = 3
                        },
                        new
                        {
                            Id = 12,
                            PostId = 11,
                            TagId = 4
                        },
                        new
                        {
                            Id = 13,
                            PostId = 12,
                            TagId = 1
                        },
                        new
                        {
                            Id = 14,
                            PostId = 13,
                            TagId = 2
                        },
                        new
                        {
                            Id = 15,
                            PostId = 14,
                            TagId = 3
                        },
                        new
                        {
                            Id = 16,
                            PostId = 15,
                            TagId = 4
                        },
                        new
                        {
                            Id = 17,
                            PostId = 16,
                            TagId = 1
                        },
                        new
                        {
                            Id = 18,
                            PostId = 17,
                            TagId = 2
                        },
                        new
                        {
                            Id = 19,
                            PostId = 18,
                            TagId = 3
                        },
                        new
                        {
                            Id = 20,
                            PostId = 19,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blocked"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3841),
                            IsDeleted = false,
                            Name = "investments",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3845),
                            IsDeleted = false,
                            Name = "boolish",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3847),
                            IsDeleted = false,
                            Name = "future",
                            UserId = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3850),
                            IsDeleted = false,
                            Name = "safe",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3284),
                            Email = "gosho@gmail.com",
                            FirstName = "Gosho",
                            IsDeleted = false,
                            LastName = "Goshev",
                            Password = "MTIzNDU2Nzg5MA==",
                            RoleId = 2,
                            Username = "goshoXx123"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3329),
                            Email = "Nikolai@gmail.com",
                            FirstName = "Nikolai",
                            IsDeleted = false,
                            LastName = "Barekov",
                            Password = "MTIzNDU2Nzg5MA==",
                            RoleId = 2,
                            Username = "BarekaXx123"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3333),
                            Email = "boko@gmail.com",
                            FirstName = "Boiko",
                            IsDeleted = false,
                            LastName = "Borisov",
                            Password = "MTIzNDU2Nzg5MA==",
                            ProfilePicPath = "/Images/UserProfilePics/936ef196-0027-4354-871e-f3fc81091f4e_00db5daec132b86843bc6692df3d369b.jpg",
                            RoleId = 2,
                            Username = "BokoMoko"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3337),
                            Email = "Cvetan@gmail.com",
                            FirstName = "Cvetan",
                            IsDeleted = false,
                            LastName = "Cvetanov",
                            Password = "MTIzNDU2Nzg5MA==",
                            ProfilePicPath = "/Images/UserProfilePics/17c63a8c-e0d2-419a-adf7-aa329feafc81_cvetan-cvetanov-pred-fakti-peevski-i-borisov-sa-partnyori-vav-vazdeistvieto-varhu-sadebnata-sistema-1.jpg",
                            RoleId = 2,
                            Username = "Cvete123"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3347),
                            Email = "Kopeikin@gmail.com",
                            FirstName = "Kosta",
                            IsDeleted = false,
                            LastName = "Kopeikin",
                            Password = "MTIzNDU2Nzg5MA==",
                            ProfilePicPath = "/Images/UserProfilePics/2b643649-b165-49e2-889a-3c2112e88ed7_0414338001637076422_1701823_920x708.jpeg",
                            RoleId = 2,
                            Username = "BrainDamage123"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3352),
                            Email = "Admin@gmail.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "Adminov",
                            Password = "MTIz",
                            ProfilePicPath = "/Images/UserProfilePics/35c6a7f8-decb-440c-853e-d32b5d0a3c64_3853-136116.jpg",
                            RoleId = 3,
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3355),
                            Email = "Andrea@gmail.com",
                            FirstName = "Andrea",
                            IsDeleted = false,
                            LastName = "Paynera",
                            Password = "MTIzNDU2Nzg5MA==",
                            ProfilePicPath = "/Images/UserProfilePics/1a630573-6728-4ac3-abd1-5acf7aebb02c_Image_13437876_40_0.jpg",
                            RoleId = 2,
                            Username = "TopAndreika"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3359),
                            Email = "Emanuela@gmail.com",
                            FirstName = "Emanuela",
                            IsDeleted = false,
                            LastName = "Paynera",
                            Password = "MTIzNDU2Nzg5MA==",
                            RoleId = 2,
                            Username = "TopEmanuelka"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3363),
                            Email = "Katrin@gmail.com",
                            FirstName = "Katrin",
                            IsDeleted = false,
                            LastName = "lilova",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "Katrin"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3368),
                            Email = "Nachosa@gmail.com",
                            FirstName = "Atanas",
                            IsDeleted = false,
                            LastName = "Iliev",
                            Password = "MTIz",
                            ProfilePicPath = "/Images/UserProfilePics/70f63493-d80b-44ed-a8cc-36e8b84b140c_photo.jpeg",
                            RoleId = 2,
                            Username = "Nachosa"
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3371),
                            Email = "Gigov@gmail.com",
                            FirstName = "Nikolai",
                            IsDeleted = false,
                            LastName = "Gigov",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "Nikolai"
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3374),
                            Email = "Vlad@gmail.com",
                            FirstName = "Vlado",
                            IsDeleted = false,
                            LastName = "Vladov",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "BatVlad"
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3378),
                            Email = "Vanko@gmail.com",
                            FirstName = "Ivan",
                            IsDeleted = false,
                            LastName = "Vanov",
                            Password = "MTIz",
                            ProfilePicPath = "/Images/UserProfilePics/6c456879-135e-482b-9ba9-bdbda1e6fe8e_309988-profileavatar.jpeg",
                            RoleId = 2,
                            Username = "BatVanko"
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3382),
                            Email = "Peshaka@gmail.com",
                            FirstName = "Petar",
                            IsDeleted = false,
                            LastName = "Ivanov",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "Peshaka"
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2023, 7, 16, 12, 52, 19, 141, DateTimeKind.Local).AddTicks(3385),
                            Email = "Gergi@gmail.com",
                            FirstName = "Georgi",
                            IsDeleted = false,
                            LastName = "Goshev",
                            Password = "MTIz",
                            ProfilePicPath = "/Images/UserProfilePics/c372cf2e-0cab-43a0-81e1-73ea610f9dfd_ddh0598-18d7e667-d117-4b11-8ef0-244eb60bfa45.jpg",
                            RoleId = 2,
                            Username = "BatGergi"
                        });
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Comment", b =>
                {
                    b.HasOne("ForumSystem.DataAccess.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumSystem.DataAccess.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Like", b =>
                {
                    b.HasOne("ForumSystem.DataAccess.Models.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ForumSystem.DataAccess.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId");

                    b.HasOne("ForumSystem.DataAccess.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Post", b =>
                {
                    b.HasOne("ForumSystem.DataAccess.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.PostTag", b =>
                {
                    b.HasOne("ForumSystem.DataAccess.Models.Post", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumSystem.DataAccess.Models.Tag", "Tag")
                        .WithMany("Posts")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Tag", b =>
                {
                    b.HasOne("ForumSystem.DataAccess.Models.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.User", b =>
                {
                    b.HasOne("ForumSystem.DataAccess.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Comment", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.Tag", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ForumSystem.DataAccess.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Posts");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
